tap "homebrew/services"
tap "minio/stable"
tap "nikitabobko/tap"
# Extendable version manager with support for Ruby, Node.js, Erlang & more
brew "asdf"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Console Matrix
brew "cmatrix"
# YAML Parser
brew "libyaml"
# Dependency manager for Cocoa projects
brew "cocoapods"
# Container runtimes on MacOS (and Linux) with minimal setup
brew "colima", restart_service: :changed
# GNU File, Shell, and Text utilities
brew "coreutils"
# Easiest way to build and release mobile apps
brew "fastlane"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# GitHub command-line tool
brew "gh"
# GNU Privacy Guard (OpenPGP)
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Generic library support script
brew "libtool"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Portable Foreign Function Interface library
brew "libffi"
# Media player based on MPlayer and mplayer2
brew "mpv"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Development kit for the Java programming language
brew "openjdk@11"
# Development kit for the Java programming language
brew "openjdk@17"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# SSL/TLS VPN implementing OSI layer 2 or 3 secure network extension
brew "openvpn"
# Python dependency management tool
brew "pipenv"
# Object-relational database system
brew "postgresql@14"
# Object-relational database system
brew "postgresql@16"
# Easily download, build, install, upgrade, and uninstall Python packages
brew "python-setuptools"
# Persistent key-value database, with built-in net interface
brew "redis", restart_service: :changed
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Prints a steam locomotive if you type sl instead of ls
brew "sl"
# Command-line interface for https://speedtest.net bandwidth tests
brew "speedtest-cli"
# Cross-shell prompt for astronauts
brew "starship"
# Terminal multiplexer
brew "tmux"
# Plugin manager for tmux
brew "tpm"
# Image processing library
brew "vips"
# Watch files and take action when they change
brew "watchman"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Tracks most-used directories to make cd smarter
brew "z"
# General-purpose lossless data-compression library
brew "zlib"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Additional completion definitions for zsh
brew "zsh-completions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
cask "aerospace"
# Tools for building Android applications
cask "android-studio"
# Open source IDE for exploring and testing APIs
cask "bruno"
# Free and open-source web browser
cask "chromium"
# Universal database tool and SQL client
cask "dbeaver-community"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
cask "font-hack-nerd-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Java IDE by JetBrains
cask "intellij-idea"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# GPU-based terminal emulator
cask "kitty"
# Clipboard manager
cask "maccy"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# Replacement for Docker Desktop
cask "orbstack"
# Collaboration platform for API development
cask "postman"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Instant messaging application focusing on security
cask "signal"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Network protocol analyzer
cask "wireshark-app"
# OpenJDK distribution from Azul
cask "zulu@17"
vscode "1yib.rust-bundle"
vscode "aaron-bond.better-comments"
vscode "anthropic.claude-code"
vscode "blanu.vscode-styled-jsx"
vscode "bradlc.vscode-tailwindcss"
vscode "burkeholland.simple-react-snippets"
vscode "catppuccin.catppuccin-vsc"
vscode "dbaeumer.vscode-eslint"
vscode "dbankier.vscode-quick-select"
vscode "decaycs.decay"
vscode "dsznajder.es7-react-js-snippets"
vscode "dustypomerleau.rust-syntax"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "fallenmax.mithril-emmet"
vscode "fill-labs.dependi"
vscode "formulahendry.auto-rename-tag"
vscode "frigus02.vscode-sql-tagged-template-literals-syntax-only"
vscode "github.vscode-github-actions"
vscode "humao.rest-client"
vscode "infeng.vscode-react-typescript"
vscode "jdinhlife.gruvbox"
vscode "johnpapa.vscode-peacock"
vscode "jwsandeman.cyberpunk2077-theme"
vscode "leonardssh.vscord"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.live-server"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "msnilshartmann.blue-light"
vscode "mushan.vscode-paste-image"
vscode "mvllow.rose-pine"
vscode "oderwat.indent-rainbow"
vscode "openai.chatgpt"
vscode "quicktype.quicktype"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "rvest.vs-code-prettier-eslint"
vscode "sdras.night-owl"
vscode "sibiraj-s.vscode-scss-formatter"
vscode "sirmspencer.vscode-autohide"
vscode "skyran.js-jsx-snippets"
vscode "stepanvanzuriak.mono"
vscode "streetsidesoftware.code-spell-checker"
vscode "swellaby.rust-pack"
vscode "tamasfe.even-better-toml"
vscode "tauri-apps.tauri-vscode"
vscode "tomoki1207.pdf"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscode-icons-team.vscode-icons"
vscode "wraith13.unsaved-files-vscode"
vscode "xabikos.javascriptsnippets"
vscode "yoavbls.pretty-ts-errors"
go "cmd/go"
go "cmd/gofmt"
npm "corepack"
