[tools]
aube = "latest"
fnox = "latest"
go = "1.26"
java = "temurin-25"
kotlin = { version = "latest", asset_pattern = "kotlin-compiler-*.zip", bin_path = "kotlinc/bin" }
node = "20.13.1"
"npm:playwright" = "latest"
"npm:vercel" = "latest"
pitchfork = "latest"
pnpm = "9.15.4"
ruby = "3.3.3"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true

[settings.ruby]
compile = false
